# Generated by Django 5.1.4 on 2025-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='desc',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contect',
            name='email',
            field=models.CharField(default='No description', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contect',
            name='name',
            field=models.CharField(default='No description', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contect',
            name='phone',
            field=models.CharField(default='No description', max_length=12),
            preserve_default=False,
        ),
    ]
