# Generated by Django 5.1.4 on 2025-01-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contect_desc_contect_email_contect_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contect',
        ),
    ]
